### ISSUE TITLE
请教一下日志相关的

### ISSUE THREAD

**Issue by c6n1aa** [xiaoxu97/mirai-plus#3]
想要在控制台上输出收到的消息和返回的消息
尝试过使用aop的方式，但好像会对指令接收造成影响，导致加了@MiraiPlusGroupMessageHandler的方法无效

**Comment by xiaoxu97** [comment]
你好，日志我是做了处理接入slf4j，目前可以通过修改日志级别为debug即可输出收到的消息和返回的消息，后续会考虑开放日志接口。
