### ISSUE TITLE
suggest：希望配置文件不要明文存储密码

### ISSUE THREAD

**Issue by Core2002** [xiaoxu97/mirai-plus#5]
比如支持md5

**Comment by xiaoxu97** [comment]
不知你想问的是哪个密码,QQ密码的话，mirai-go本身支持加密存储，如果是连接密码的话，连接密码的本质是验证连接是否有效，而这个判定规则是mirai-go提出的，不存储明文无非就是怕泄露，但是你存md5的话没有任何意义，因为这样的话mirai-go配置的也得是md5，而且大多数使用场景都是内网，这功能可以做，但意义不大。

**Comment by Core2002** [comment]
application.yml里的botPassword

**Comment by xiaoxu97** [comment]
奥 我看错项目了。。。
这个项目很久没维护了，这个密码也没加密的必要，因为这个文件不应该暴露出去，可以看看我的新项目[go-cqhttp/java](https://github.com/go-cqhttp/java)
